#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: ./testDescribe testSetFile" >&2
fi

while read -r stem; do
    if [ -e "$stem.desc" ]; then
        cat "$stem.desc"
    else
        echo "$stem No test description"
    fi
done < "$1"