#!/bin/bash

 for stem in $(cat $2); do
    echo $stem
    if [ -e "$stem.in" ]; then
        $1 < $stem.in > "actual.out"
        diff -q actual.out $stem.out 1>/dev/null
        if [[ $? == "0" ]]; then
            echo "Test stem passed"
        else
            echo "Test stem failed"
            echo "Expected output:"
            cat $stem.out
            echo "Actual output:"
            cat actual.out
        fi
    fi
    rm actual.out
done
