#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: ./testDescribe testSetFile" >&2
    exit 1
fi

for stem in $(cat $1); do
    if [ -e "$stem.desc" ]; then
        cat "$stem.desc"
    else
        echo "$stem No test description"
    fi
done