#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 testSetFile" >&2
else
    for stem in $(cat "$1"); do
        if [ -f "$stem.desc" ]; then
            cat "$stem.desc"
        else
            echo "$stem No test description"
        fi
    done
fi
